---
language: ruby
sudo: required
services:
  - docker
script:
  - bundle exec rspec spec/acceptance
bundler_args: --without system_tests
matrix:
  include:
  - rvm: default
    env: BEAKER_set="centos6-docker"
    dist: trusty
    bundler_args:
    script: sudo yum install java-1.7.0-openjdk-devel -y; sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
